function apagarMedidas() {
    document.getElementById("s1").value = "";
    document.getElementById("s2").value = "";
    document.getElementById("s3").value = "";
    document.getElementById("s4").value = "";
    document.getElementById("s5").value = "";
    document.getElementById("s6").value = "";
    document.getElementById("s7").value = "";
    document.getElementById("s8").value = "";
    document.getElementById("s9").value = "";
    document.getElementById("s10").value = "";
    document.getElementById("s11").value = "";
    document.getElementById("s12").value = "";
    document.getElementById("s13").value = "";
    document.getElementById("s14").value = "";
    document.getElementById("s15").value = "";
    document.getElementById("s16").value = "";
    document.getElementById("s17").value = "";
    document.getElementById("s18").value = "";
    document.getElementById("s19").value = "";
    document.getElementById("s20").value = "";
    document.getElementById("s21").value = "";
    document.getElementById("s22").value = "";
    document.getElementById("s23").value = "";
    document.getElementById("s24").value = "";
    document.getElementById("s25").value = "";
    document.getElementById("s26").value = "";
    document.getElementById("s27").value = "";
    document.getElementById("s28").value = "";
    document.getElementById("s29").value = "";
    document.getElementById("s30").value = "";
    document.getElementById("s31").value = "";
    document.getElementById("s32").value = "";
    document.getElementById("s33").value = "";
    document.getElementById("s34").value = "";
    document.getElementById("s35").value = "";
}

document.getElementById("apagarMedidas").addEventListener("click", apagarMedidas);